name: andrhelper_client
description: "Android interview helper client for ANDRHELPER"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  flutter_markdown: ^0.7.4+3
  http: ^1.2.0
  permission_handler: ^11.3.1
  record: ^6.1.2
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.3
  googleapis_auth: ^1.4.1
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


